# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Container",
    "KeyEvent",
    "Terminal",
    "Text",
    "Tree",
    "container",
    "terminal_size",
    "text",
]

@typing.final
class Container:
    r"""
    A container stacking `children` along `layout`'s axis
    (`RSACT_LAYOUT_VERTICAL`/`_HORIZONTAL`). Immutable, plain data — build
    one with `container()`, not directly.
    """
    @property
    def key(self) -> builtins.str: ...
    @property
    def layout(self) -> builtins.int: ...
    @property
    def children(self) -> builtins.list[typing.Any]: ...
    @property
    def width(self) -> builtins.int: ...
    @property
    def height(self) -> builtins.int: ...

@typing.final
class KeyEvent:
    r"""
    A decoded key. `char` is set for a printable character, `special` for
    one of the `RSACT_KEY_*` constants — exactly one of the two.
    """
    @property
    def char(self) -> typing.Optional[builtins.str]: ...
    @property
    def special(self) -> typing.Optional[builtins.int]: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Terminal:
    r"""
    The flat cell-buffer API: draw with `set_cell`, then `render` to
    diff-and-flush just the changed cells to the terminal in one write.
    
    `unsendable`: holds a `RawModeGuard` (owns the terminal's raw-mode
    state via a `Box<dyn Write>`), which isn't `Send`/`Sync` — matches
    `rsact-ffi`'s own documented constraint of one thread at a time.
    """
    def __new__(cls, width: builtins.int, height: builtins.int) -> Terminal: ...
    def set_cell(self, row: builtins.int, col: builtins.int, ch: builtins.str, fg: builtins.int = 16777215, bg: builtins.int = 0, bold: builtins.bool = False, underline: builtins.bool = False, reverse: builtins.bool = False) -> None: ...
    def render(self) -> None: ...
    def poll_key(self) -> typing.Optional[KeyEvent]: ...
    def close(self) -> None:
        r"""
        Restores the terminal immediately, without waiting for this object
        to be garbage-collected. Not required for correctness — dropping
        (or letting the last reference go out of scope) does the same
        thing automatically, via Rust's own `Drop` on the `RawModeGuard`
        this holds — this is only for when you want that to happen at a
        specific point instead of whenever GC gets to it.
        """

@typing.final
class Text:
    r"""
    A single-line text leaf. Immutable, plain data — build one with
    `text()`, not directly.
    """
    @property
    def key(self) -> builtins.str: ...
    @property
    def content(self) -> builtins.str: ...
    @property
    def width(self) -> builtins.int: ...
    @property
    def fg(self) -> builtins.int: ...
    @property
    def bg(self) -> builtins.int: ...
    @property
    def bold(self) -> builtins.bool: ...
    @property
    def underline(self) -> builtins.bool: ...
    @property
    def reverse(self) -> builtins.bool: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...

@typing.final
class Tree:
    r"""
    The component-tree API: build a fresh `Text`/`Container` tree every
    frame (plain, immutable data — see `text()`/`container()`) and call
    `present`, which compiles it to native elements, reconciles it against
    the previous frame, and draws only what changed.
    
    `unsendable`: see `Terminal`'s doc comment — same reason.
    """
    def __new__(cls, width: builtins.int, height: builtins.int) -> Tree: ...
    def present(self, node: typing.Any) -> None: ...
    def poll_key(self) -> typing.Optional[KeyEvent]: ...
    def close(self) -> None:
        r"""
        Restores the terminal immediately, without waiting for this object
        to be garbage-collected. Not required for correctness — dropping
        (or letting the last reference go out of scope) does the same
        thing automatically, via Rust's own `Drop` on the `RawModeGuard`
        this holds — this is only for when you want that to happen at a
        specific point instead of whenever GC gets to it.
        """

def container(key: builtins.str, layout: builtins.int, children: typing.Sequence[typing.Any] = [], width: builtins.int = 0, height: builtins.int = 0) -> Container:
    r"""
    Builds a `Container`, stacking `children` (a list of `text()`/
    `container()` results) along `layout`'s axis.
    """

def terminal_size() -> tuple[builtins.int, builtins.int]:
    r"""
    Returns `(rows, cols)` of the current terminal.
    """

def text(key: builtins.str, content: builtins.str, width: builtins.int = 0, fg: builtins.int = 16777215, bg: builtins.int = 0, bold: builtins.bool = False, underline: builtins.bool = False, reverse: builtins.bool = False) -> Text:
    r"""
    Builds a `Text` leaf.
    """

